import { Button, Modal, Space, Tag, Typography, message } from 'antd';
import { PlayCircleOutlined, StopOutlined, VideoCameraAddOutlined } from '@ant-design/icons';
import { useRef, useState } from 'react';
import { unifiedApi } from '../../unifiedApi.js';

interface RrEvent { type: number; timestamp: number; data: unknown }
type RecordFn=(options:{emit:(event:RrEvent)=>void;checkoutEveryNms:number;maskInputOptions:{password:boolean}})=>(()=>void)|undefined;

export function RrwebRecorder(){const events=useRef<RrEvent[]>([]);const stop=useRef<(()=>void)>();const [recording,setRecording]=useState(false);const [preview,setPreview]=useState<RrEvent[]>();const [busy,setBusy]=useState(false);const start=async()=>{try{const mod=await import('rrweb');const record=(mod as unknown as {record:RecordFn}).record;events.current=[];stop.current=record({emit:(event)=>events.current.push(event),checkoutEveryNms:30000,maskInputOptions:{password:true}});if(!stop.current)throw new Error('录制器启动失败');setRecording(true);message.info('rrweb 已开始录制');}catch(e){message.error((e as Error).message);}};const finish=async()=>{stop.current?.();stop.current=undefined;setRecording(false);setPreview([...events.current]);setBusy(true);try{const content={format:'team-manager-rrweb',version:1,createdAt:new Date(events.current[0]?.timestamp??Date.now()).toISOString(),endedAt:new Date().toISOString(),page:{url:location.href,title:document.title,viewport:{width:innerWidth,height:innerHeight,devicePixelRatio}},events:events.current};const jsonBytes=new TextEncoder().encode(JSON.stringify(content));const stream=new Blob([jsonBytes as Uint8Array<ArrayBuffer>]).stream().pipeThrough(new CompressionStream('gzip'));const bytes=new Uint8Array(await new Response(stream).arrayBuffer());const result=await unifiedApi.uploadRrweb(bytes,`${Date.now()}.json.gz`,content.createdAt);message.success(`录制已保存：${result.id}`);}catch(e){message.error(`上传失败：${(e as Error).message}`);}finally{setBusy(false);}};return <><div className="rrweb-dev-tools" data-rrweb-ignore><Space wrap><Tag color={recording?'error':'processing'}>rrweb</Tag>{recording?<><Typography.Text>{events.current.length} 个事件</Typography.Text><Button danger icon={<StopOutlined/>} onClick={()=>void finish()}>停止并上传</Button></>:<Button icon={<VideoCameraAddOutlined/>} loading={busy} onClick={()=>void start()}>开始录制</Button>}{preview&&<Button icon={<PlayCircleOutlined/>} onClick={()=>setPreview([...preview])}>查看最近原文</Button>}</Space></div><Modal title="最近 rrweb 原文" open={Boolean(preview)&&!recording} onCancel={()=>setPreview(undefined)} footer={null} width="min(900px,94vw)"><Typography.Paragraph type="secondary">当前版本提供完整事件原文和文件制品页下载；可视化播放器由后端返回标准 recording 后加载。</Typography.Paragraph><Typography.Text code>{JSON.stringify(preview)?.slice(0,10000)}</Typography.Text></Modal></>}
