import { useEffect, useState } from 'react';
import { Alert, Button, Card, Form, Input, Space, Switch, Table, Tabs, Tag } from 'antd';
import { unifiedApi, type CredentialPoolGroupView, type NotificationDeliveryView } from '../../unifiedApi.js';
import { JsonViewer, LoadBoundary, PageHeader, formatTime } from '../../components/ProductPrimitives.js';

export function SettingsPage() {
  const [policies,setPolicies]=useState<Array<Record<string,unknown>>>([]); const [deliveries,setDeliveries]=useState<NotificationDeliveryView[]>([]); const [groups,setGroups]=useState<CredentialPoolGroupView[]>([]); const [settings,setSettings]=useState<Array<{key:string;value?:Record<string,unknown>}>>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const result=await Promise.allSettled([unifiedApi.notificationPolicies(),unifiedApi.notificationDeliveries(),unifiedApi.credentialPoolGroups(),unifiedApi.systemSettings()]);if(result[0].status==='fulfilled')setPolicies(result[0].value);if(result[1].status==='fulfilled')setDeliveries(result[1].value);if(result[2].status==='fulfilled')setGroups(result[2].value);if(result[3].status==='fulfilled')setSettings(result[3].value);}catch(e){setError((e as Error).message);}finally{setLoading(false);}};useEffect(()=>{void load();},[]);const run=async(key:string,action:()=>Promise<unknown>)=>{setBusy(key);setError('');try{await action();await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}};
  return <Space direction="vertical" size={16} className="panel-stack"><Card><PageHeader title="系统设置" description="通知、号池分组和个人表单偏好统一保存到 PostgreSQL"/></Card>{error&&<Alert type="error" showIcon message={error}/>}<Card><LoadBoundary loading={loading} error={error} onRetry={load}><Tabs items={[
    {key:'notifications',label:'通知策略',children:<Space direction="vertical" className="panel-stack"><Table rowKey={(r)=>String(r.kind)} pagination={false} dataSource={policies} scroll={{x:900}} columns={[{title:'策略',dataIndex:'kind'},{title:'启用',dataIndex:'enabled',render:(v)=>v?<Tag color="green">是</Tag>:'否'},{title:'配置',dataIndex:'configuration',render:(v)=><JsonViewer title="查看完整配置" value={v}/>},{title:'操作',render:(_,r)=><Button loading={busy===`test-${r.kind}`} onClick={()=>run(`test-${r.kind}`,()=>unifiedApi.testNotificationPolicy(String(r.kind)))}>发送测试</Button>}]}/><Form layout="vertical" onFinish={async(value)=>{let configuration={};try{configuration=value.configuration?JSON.parse(value.configuration):{};}catch{setError('配置必须是 JSON 对象');return;}await run('policy',()=>unifiedApi.saveNotificationPolicy(value.kind,{enabled:value.enabled===true,configuration}));}}><div className="responsive-form-grid"><Form.Item name="kind" label="策略键" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="enabled" label="启用" valuePropName="checked"><Switch/></Form.Item></div><Form.Item name="configuration" label="配置 JSON"><Input.TextArea rows={6}/></Form.Item><Button htmlType="submit" type="primary" loading={busy==='policy'}>保存通知策略</Button></Form></Space>},
    {key:'deliveries',label:`投递历史 (${deliveries.length})`,children:<Table rowKey="id" dataSource={deliveries} scroll={{x:900}} columns={[{title:'时间',dataIndex:'createdAt',render:formatTime},{title:'策略',dataIndex:'kind'},{title:'状态',dataIndex:'status',render:(v)=><Tag>{v}</Tag>},{title:'错误',dataIndex:'error'},{title:'原始载荷',dataIndex:'payload',render:(v)=><JsonViewer title="查看" value={v}/>} ]}/>},
    {key:'pools',label:`凭证号池组 (${groups.length})`,children:<Space direction="vertical" className="panel-stack">{groups.map((group)=><Form key={group.id} layout="inline" initialValues={{name:group.name}} onFinish={(v)=>run(`group-${group.id}`,()=>unifiedApi.updateCredentialPoolGroup(group.id,v))}><Form.Item name="name"><Input/></Form.Item><Button htmlType="submit">重命名</Button><Button danger disabled={Boolean(group.credentialCount)} onClick={()=>run(`delete-${group.id}`,()=>unifiedApi.deleteCredentialPoolGroup(group.id))}>删除</Button><span>{group.credentialCount??0} 个凭证</span></Form>)}<Form layout="inline" onFinish={(v)=>run('new-group',()=>unifiedApi.createCredentialPoolGroup(v.name))}><Form.Item name="name" rules={[{required:true}]}><Input placeholder="新号池组名称"/></Form.Item><Button type="primary" htmlType="submit">创建号池组</Button></Form></Space>},
    {key:'preferences',label:'系统与表单偏好',children:<Form layout="vertical" initialValues={settings.find((row)=>row.key==='web.preferences')?.value} onFinish={(v)=>run('settings',()=>unifiedApi.saveSystemSetting('web.preferences',v))}><div className="switch-grid"><Form.Item name="rememberFormValues" label="记住表单值" valuePropName="checked"><Switch/></Form.Item><Form.Item name="autoRefreshOperations" label="自动刷新操作" valuePropName="checked"><Switch/></Form.Item><Form.Item name="rrwebEnabled" label="启用 rrweb 录制" valuePropName="checked"><Switch/></Form.Item></div><Form.Item name="artifactRetentionDays" label="文件制品保留天数"><Input type="number"/></Form.Item><Button htmlType="submit" type="primary">保存系统设置</Button><JsonViewer title="系统设置原始 JSON" value={settings}/></Form>}
  ]}/></LoadBoundary></Card></Space>;
}
