import { useEffect, useMemo, useState } from 'react';
import { Alert, Button, Card, Descriptions, Form, Input, Modal, Select, Space, Table, Tabs, Tag, Typography } from 'antd';
import { useParams, useSearchParams } from 'react-router-dom';
import type { OpenBusinessSubscriptionRequest, UnifiedAccountSummaryView, WorkspaceDetailView } from '@team-manager/shared';
import { unifiedApi } from '../../unifiedApi.js';

export function WorkspaceDetailPage() {
  const {workspaceId}=useParams(); const [params,setParams]=useSearchParams(); const [workspace,setWorkspace]=useState<WorkspaceDetailView>(); const [accounts,setAccounts]=useState<UnifiedAccountSummaryView[]>([]); const [error,setError]=useState('');
  const load=async()=>{if(!workspaceId)return;try{const [w,a]=await Promise.all([unifiedApi.workspace(workspaceId),unifiedApi.accounts(new URLSearchParams('hasManageableWorkspace=true'))]);setWorkspace(w);setAccounts(a);}catch(e){setError((e as Error).message);}}; useEffect(()=>{void load();},[workspaceId]);
  const executors=useMemo(()=>workspace?.members.filter(m=>m.accountId&&['owner','admin'].includes(m.role))??[],[workspace]); const tab=params.get('tab')??'overview'; const modal=params.get('modal'); const set=(k:string,v?:string)=>{const n=new URLSearchParams(params);v?n.set(k,v):n.delete(k);setParams(n);};
  if(!workspace)return <Card loading={!error}>{error&&<Alert type="error" message={error}/>}</Card>;
  return <Space direction="vertical" size={16} style={{width:'100%'}}><Card><Space style={{width:'100%',justifyContent:'space-between'}}><div><Typography.Text type="secondary">Workspace</Typography.Text><Typography.Title level={2} style={{margin:0}}>{workspace.name??workspace.externalId}</Typography.Title></div><Button onClick={()=>set('modal','business')}>Business 套餐</Button></Space></Card><Card><Tabs activeKey={tab} onChange={v=>set('tab',v)} items={[
    {key:'overview',label:'概览',children:<Descriptions bordered items={[{key:'id',label:'外部 ID',children:workspace.externalId},{key:'plan',label:'套餐',children:<Tag>{workspace.plan}</Tag>},{key:'manager',label:'可管理账号',children:workspace.manageableAccountCount},{key:'renew',label:'下次续费',children:workspace.nextRenewalAt??'—'}]}/>},
    {key:'members',label:`成员 (${workspace.members.length})`,children:<Table rowKey="id" dataSource={workspace.members} columns={[{title:'成员',render:(_,r)=>r.email??r.accountEmail??r.remoteUserId},{title:'角色',dataIndex:'role'},{title:'席位',dataIndex:'seatType'},{title:'状态',dataIndex:'status'}]}/>},
    {key:'invitations',label:`邀请 (${workspace.invitations.length})`,children:<Table rowKey="id" dataSource={workspace.invitations} columns={[{title:'邮箱',dataIndex:'email'},{title:'角色',dataIndex:'role'},{title:'席位',dataIndex:'seatType'},{title:'状态',dataIndex:'status'}]}/>},
    {key:'seats',label:`客户席位 (${workspace.seatSlots.length})`,children:<Table rowKey="id" dataSource={workspace.seatSlots} columns={[{title:'邮箱',dataIndex:'email'},{title:'访问键',dataIndex:'seatKey'},{title:'到期',dataIndex:'expiresOn'},{title:'状态',dataIndex:'status'}]}/>},
    {key:'credentials',label:`凭证 (${workspace.credentials.length})`,children:<Table rowKey="id" dataSource={workspace.credentials} columns={[{title:'账号',dataIndex:'accountEmail'},{title:'类型',dataIndex:'kind'},{title:'状态',dataIndex:'status'},{title:'哈希',dataIndex:'contentSha256',ellipsis:true}]}/>},
    {key:'settings',label:'设置与账单',children:<Space direction="vertical" style={{width:'100%'}}><Typography.Title level={4}>设置快照</Typography.Title><pre>{JSON.stringify(workspace.latestSettings?.payload??{},null,2)}</pre><Typography.Title level={4}>账单快照</Typography.Title><pre>{JSON.stringify(workspace.latestBilling?.payload??{},null,2)}</pre></Space>}
  ]}/></Card><Modal title="升级为 Business" open={modal==='business'} onCancel={()=>set('modal')} footer={null}><Form layout="vertical" initialValues={{mode:'upgrade_existing_workspace',workspaceId:workspace.id,country:'US',currency:'USD',autoPay:false}} onFinish={async(v:OpenBusinessSubscriptionRequest&{accountId:string})=>{await unifiedApi.openBusiness(v.accountId,v);set('modal');}}><Form.Item name="accountId" label="执行账号" rules={[{required:true}]}><Select options={executors.map(m=>({value:m.accountId!,label:m.accountEmail??m.email??m.accountId}))}/></Form.Item><Form.Item name="mode" hidden><Input/></Form.Item><Form.Item name="workspaceId" hidden><Input/></Form.Item><Space><Form.Item name="country" label="国家"><Input/></Form.Item><Form.Item name="currency" label="货币"><Input/></Form.Item></Space><Form.Item name="promoCode" label="优惠码"><Input/></Form.Item><Button type="primary" htmlType="submit">创建升级操作</Button></Form></Modal></Space>;
}
