import { readFile, readdir, stat, unlink } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import type { Kysely } from 'kysely';
import type { Database } from '../database/schema.js';
import { ArtifactStore } from '../artifactStore.js';
import { CredentialRepository } from '../repositories/credentialRepository.js';
import { ServiceError } from '../serviceError.js';
import { sha256 } from '../secretCipher.js';

export class ArtifactService {
  readonly #credentials:CredentialRepository;
  constructor(private readonly db:Kysely<Database>,private readonly store:ArtifactStore,private readonly root:string){this.#credentials=new CredentialRepository(db,store);}
  async list(kind?:string,limit=500){const max=Math.min(Math.max(limit,1),2000);const output:any[]=[];if(!kind||kind==='trace')for(const r of await this.db.selectFrom('upstream_trace_segments').selectAll().orderBy('recorded_at','desc').limit(max).execute())output.push(view('trace',r));if(!kind||kind==='rrweb')for(const r of await this.db.selectFrom('rrweb_recordings').selectAll().orderBy('recorded_at','desc').limit(max).execute())output.push(view('rrweb',r));if(!kind||kind==='credential')for(const r of await this.db.selectFrom('workspace_credentials').selectAll().orderBy('created_at','desc').limit(max).execute())output.push({id:r.id,kind:'credential',storageKey:r.storage_key,contentSha256:r.content_sha256,byteSize:Number(r.byte_size),status:r.status,recordedAt:new Date(r.created_at as any).toISOString(),metadata:{accountId:r.account_id,workspaceId:r.workspace_id,credentialKind:r.kind}});if(!kind||kind==='quarantine')for(const r of await this.db.selectFrom('quarantined_artifacts').selectAll().orderBy('created_at','desc').limit(max).execute())output.push({id:r.id,kind:'quarantine',storageKey:r.storage_key,contentSha256:r.content_sha256,byteSize:Number(r.byte_size),status:r.status,recordedAt:new Date(r.created_at as any).toISOString(),metadata:r.metadata});if(kind==='orphan')for(const r of await this.db.selectFrom('artifact_orphans').selectAll().orderBy('discovered_at','desc').limit(max).execute())output.push({id:r.id,kind:'orphan',storageKey:r.storage_key,contentSha256:r.content_sha256,byteSize:Number(r.byte_size),status:r.status,recordedAt:new Date(r.discovered_at as any).toISOString(),expiresAt:new Date(r.delete_after as any).toISOString(),metadata:r.metadata});return output.sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt)).slice(0,max);}
  async read(kind:string,id:string){if(kind==='trace'||kind==='rrweb'){const table=kind==='trace'?'upstream_trace_segments' as const:'rrweb_recordings' as const;const r=await this.db.selectFrom(table).selectAll().where('id','=',id).executeTakeFirst();if(!r)throw new ServiceError(404,'制品不存在');return this.store.read(r.storage_key,r.content_sha256);}if(kind==='credential')return this.#credentials.read(id);if(kind==='quarantine'){const r=await this.db.selectFrom('quarantined_artifacts').selectAll().where('id','=',id).executeTakeFirst();if(!r)throw new ServiceError(404,'隔离制品不存在');return this.store.read(r.storage_key,r.content_sha256);}if(kind==='orphan'){const r=await this.db.selectFrom('artifact_orphans').selectAll().where('id','=',id).where('status','=','pending_delete').executeTakeFirst();if(!r)throw new ServiceError(404,'孤儿制品不存在');return this.store.read(r.storage_key,r.content_sha256);}throw new ServiceError(400,'无效制品类型');}
  async markDelete(kind:string,id:string,graceMs=24*3600_000){if(kind!=='trace'&&kind!=='rrweb')throw new ServiceError(409,'凭证请使用凭证生命周期 API');const table=kind==='trace'?'upstream_trace_segments' as const:'rrweb_recordings' as const;const row=await this.db.updateTable(table).set({status:'pending_delete',expires_at:new Date(Date.now()+graceMs)}).where('id','=',id).returning('id').executeTakeFirst();if(!row)throw new ServiceError(404,'制品不存在');return true;}
  async claimQuarantine(id:string,input:{accountId:string;workspaceId:string;kind:'oauth'|'pat';poolGroupId?:string}){const row=await this.db.selectFrom('quarantined_artifacts').selectAll().where('id','=',id).where('status','=','quarantined').executeTakeFirst();if(!row)throw new ServiceError(404,'隔离凭证不存在');const content=await this.store.read(row.storage_key,row.content_sha256);const saved=await this.#credentials.save({accountId:input.accountId,workspaceId:input.workspaceId,kind:input.kind,fileName:`claimed-${id}.json`,content,poolGroupId:input.poolGroupId});await this.db.updateTable('quarantined_artifacts').set({status:'claimed'}).where('id','=',id).execute();return{id:saved.id};}
  async discardQuarantine(id:string){const row=await this.db.updateTable('quarantined_artifacts').set({status:'discarded'}).where('id','=',id).where('status','=','quarantined').returning('id').executeTakeFirst();if(!row)throw new ServiceError(404,'隔离凭证不存在');return true;}
  async cleanup(now=new Date()){let removed=0,failed=0,retained=0,discovered=0;const retention=await this.db.selectFrom('system_settings').select('value').where('key','=','artifact_retention').executeTakeFirst();const traceDays=Number(retention?.value.traceDays??30),rrwebDays=Number(retention?.value.rrwebDays??14),graceMs=Math.max(Number(retention?.value.graceHours??24),1)*3600_000;for(const [,table,days] of [['trace','upstream_trace_segments',traceDays],['rrweb','rrweb_recordings',rrwebDays]] as const){const cutoff=new Date(now.getTime()-Math.max(days,1)*86400_000);const active=await this.db.selectFrom(table).select('id').where('status','=','active').where('recorded_at','<',cutoff).execute();for(const row of active)await this.db.updateTable(table).set({status:'pending_delete',expires_at:new Date(now.getTime()+graceMs)}).where('id','=',row.id).execute();retained+=active.length;const rows=await this.db.selectFrom(table).selectAll().where('status','=','pending_delete').where('expires_at','<=',now).execute();for(const row of rows){try{await unlink(this.store.resolveStorageKey(row.storage_key)).catch(e=>{if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;});await this.db.deleteFrom(table).where('id','=',row.id).execute();removed+=1;}catch{failed+=1;}}}
    const known=await this.knownStorageKeys();
    for(const file of await this.orphanFiles(known)){try{const storageKey=relative(this.root,file);const content=await readFile(file);const contentSha256=sha256(content);const existing=await this.db.selectFrom('artifact_orphans').selectAll().where('storage_key','=',storageKey).executeTakeFirst();if(!existing){await this.db.insertInto('artifact_orphans').values({storage_key:storageKey,content_sha256:contentSha256,byte_size:content.byteLength,status:'pending_delete',discovered_at:now,delete_after:new Date(now.getTime()+graceMs),deleted_at:null,metadata:{reason:'unindexed_file'}}).execute();discovered+=1;}else if(existing.status!=='pending_delete'||existing.content_sha256!==contentSha256||Number(existing.byte_size)!==content.byteLength){await this.db.updateTable('artifact_orphans').set({content_sha256:contentSha256,byte_size:content.byteLength,status:'pending_delete',discovered_at:now,delete_after:new Date(now.getTime()+graceMs),deleted_at:null,metadata:{reason:'rediscovered_or_changed_unindexed_file'}}).where('id','=',existing.id).execute();discovered+=1;}}catch{failed+=1;}}
    const pending=await this.db.selectFrom('artifact_orphans').selectAll().where('status','=','pending_delete').execute();
    for(const row of pending){if(known.has(row.storage_key)){await this.db.deleteFrom('artifact_orphans').where('id','=',row.id).execute();continue;}if(new Date(row.delete_after as any)>now)continue;try{await unlink(this.store.resolveStorageKey(row.storage_key));await this.db.updateTable('artifact_orphans').set({status:'deleted',deleted_at:now}).where('id','=',row.id).execute();removed+=1;}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT'){await this.db.updateTable('artifact_orphans').set({status:'missing',deleted_at:now}).where('id','=',row.id).execute();}else failed+=1;}}
    const orphans=await this.db.selectFrom('artifact_orphans').select(({fn})=>fn.countAll<number>().as('count')).where('status','=','pending_delete').executeTakeFirstOrThrow();return{removed,failed,retained,orphans:Number(orphans.count),discovered};}
  async verify(){let checked=0,failed=0;for(const item of await this.list(undefined,2000)){try{await this.store.verify(item.storageKey,item.contentSha256,item.byteSize);checked+=1;}catch{failed+=1;}}return{checked,failed};}
  private async knownStorageKeys(){return new Set((await this.list(undefined,10000)).map(x=>x.storageKey));}
  private async orphanFiles(known:Set<string>){const files:string[]=[];for(const kind of ['credentials','credential-quarantine','rrweb','traces']){const base=resolve(this.root,kind);for(const file of await walk(base)){const key=relative(this.root,file);if(!known.has(key))files.push(file);}}return files;}
}
function view(kind:string,r:any){return{id:r.id,kind,storageKey:r.storage_key,contentSha256:r.content_sha256,byteSize:Number(r.byte_size),status:r.status,recordedAt:new Date(r.recorded_at).toISOString(),...(r.expires_at?{expiresAt:new Date(r.expires_at).toISOString()}:{}),metadata:r.metadata};}
async function walk(path:string):Promise<string[]>{try{const entries=await readdir(path,{withFileTypes:true});const out:string[]=[];for(const e of entries){const p=resolve(path,e.name);if(e.isDirectory())out.push(...await walk(p));else if(e.isFile()&&(await stat(p)).size>=0)out.push(p);}return out;}catch(error){return (error as NodeJS.ErrnoException).code==='ENOENT'?[]:Promise.reject(error);}}
export function startArtifactCleanupScheduler(service:ArtifactService,intervalMs=60*60_000){const timer=setInterval(()=>void service.cleanup().catch(e=>console.warn('[team-manager] 制品清理失败:',e)),intervalMs);timer.unref();return()=>clearInterval(timer);}
